@startuml
participant Admin
participant Player1
participant Player2
participant Dealer
participant Game

Player1 -> Dealer: Register
Dealer --> Player1: Ok
Player2 -> Dealer: Register
Dealer --> Player2: Ok

Admin -> Dealer: Launch(Player1, Player2)
Dealer -> Player1: Check
Player1 --> Dealer: Ok
Dealer -> Player2: Check
Player2 --> Dealer: Ok
Dealer --> Admin: Ok

Dealer -> Game: Init
Game --> Dealer: Match

loop
  Dealer -> Player1: Play(Match)
  Player1 --> Dealer: Action
  Dealer -> Game: Apply(Action, Match)
  Game --> Dealer: Match

  Dealer -> Player2: Play(Match)
  Player2 --> Dealer: Action
  Dealer -> Game: Apply(Action, Match)
  Game --> Dealer: Match
end

Dealer -> Player1: Notify
Player1 --> Dealer: Ok
Dealer -> Player2: Notify
Player2 --> Dealer: Ok

@enduml
